server:
  port: 8040
spring:
  application:
    name: microservice-gateway-zuul
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ 

zuul: 
  max: 
    host: 
     connections: 500 
  host: 
    # 设置超时
    socket-timeout-millis: 60000 
    connect-timeout-millis: 60000
  routes: 
    microservice-consumer-movie: /movie/**
    microservice-provider-user: 
      path: /user/**
      sensitive-headers: Cookie,Set-Cookie,Authorization 

# 设置超时
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1

# 设置超时
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 60000
